### PR TITLE
Fix deprecation warnings & webview duplicate

### PR DESCRIPTION
**Pull request by IntelliJAbhishek**
- componentWillReceiveProps
- componentWillUpdate
- if someone using latest webview and use this repo they will get duplicate webview beacuse this libray uses webview as dependency

### CODE REVIEW

**Comment by IntelliJAbhishek** [comment]
@ThomasHenrissat , @chr314 m @Exilz  please review and merge guyz. its very important

**Comment by chr314** [comment]
Hi @IntelliJAbhishek 
I can't merge it, I'm not a maintainer

**Comment by IjzerenHein** [comment]
Agree, this is an important PR 👍 

I'm skeptical about this part of the PR though:

> if someone using latest webview and use this repo they will get duplicate webview beacuse this libray uses webview as dependency

@IntelliJAbhishek can you elaborate on why you would want this? 

As it stands now, the web-view is  a hard requirement and needs to be installed (it's not an optional dependency, even though you might not be using iframes at all). So if this is something that the user needs to install explicitly, then it should also be included in the Installation docs.

Apart from the fact that the web-view dependency change should be a separate PR imo (let's make it as easy as possible for maintainers to pull in isolated changes..), I think the web-view should remain a regular dependency as it previously was. If you want to ensure that a certain version of the webview package is resolved, then you should use [`package.json resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)

**Comment by aranda-adapptor** [comment]
Tested this on a project that does not use `react-native-webview` explicitly and it fails loading the bundle:

```
Unable to resolve module `react-native-webview` from `/Users/aranda/project/node_modules/react-native-render-html/src/HTMLRenderers.js`: Module `react-native-webview` does not exist in the Haste module map
```

**Comment by IntelliJAbhishek** [comment]
@aranda-adapptor you need to intall react-native-webview if you are esting this commit

**Comment by bd-arc** [comment]
Available in version `4.2.0`

**Pull request closed without merging**
