### PR TITLE
chore(ci): add github workflow for testing

### PR DESCRIPTION
**Pull request by jsamr**
@Exilz I have tested this github workflow on my fork, and it works. ~~I don't know how well is it integrated to PRs yet, though.~~

### CODE REVIEW

**Comment by Exilz** [comment]
Fantastic ! As for PRs, you can set up checks that may or may not be required to prevent PRs from being merged if tests fail.

**Comment by Exilz** [comment]
Now that I think about it, a couple of CI badges on top of the README would be really nice too 😄

**Comment by jsamr** [comment]
@Exilz We had the same idea!

**Comment by jsamr** [comment]
@Exilz Here you go ;-) dc0599818e236663e9a8b9574da05b4142ac8e9d

**Pull request merged**
